# Generated by Django 2.2.7 on 2019-12-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
    ]
